AWSTemplateFormatVersion: 2010-09-09
Description: "This template creates a VPC with a single ec2 instance, the instance will get apache installed on it."
Resources:
  myVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      EnableDnsHostnames: "true"
      EnableDnsSupport: "true"
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value:
            Ref: AWS::StackName
  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value:
            !Ref AWS::StackName
  myVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId:
        !Ref myInternetGateway
      VpcId:
        !Ref myVPC
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      MapPublicIpOnLaunch: "true"
      VpcId:
        !Ref myVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value:
            !Sub ${AWS::StackName}-PublicSubnet1
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} Public Routes
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: myVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref myInternetGateway
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1
Outputs:
  subnet:
    Value: !Ref PublicSubnet1
    Export:
      Name:
        !Sub ${AWS::StackName}-subnet
  vpc:
    Value: !Ref myVPC
    Export:
      Name:
        !Sub ${AWS::StackName}-vpc
